language: python
python:
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
before_script:
  - pip install -r test_requirements.txt
script:
  - py.test --doctest-modules --pep8 fanart -v --cov fanart --cov-report term-missing
after_success:
  - coveralls
